use cs043;
create table rest(ID varchar(10) primary key,name varchar(50), loc varchar(50), rating float);
select * from rest;
insert into rest values("007", "Chinese Square", "Basavanagudi",null);
insert into rest values("006", "Rolls on Wheels", "Hanumanthnagar",null);
insert into rest values("005", "Bhavani", "Bull Temple Road",null);
insert into rest values("004", "Schezwan Dragon", "Above Rolls on Wheels",null);
insert into rest values("003", "Utsav", "Behind BMSCE",null);
insert into rest values("002", "RoofTop", "Jayanagar",null);
insert into rest values("001", "Meghana Foods", "Across Bengaluru",null);
create table rev(CID varchar(10) primary key, name varchar(50),ID varchar(10), foreign key(ID) references rest(ID));
alter table rev add column(rating int check (rating <6 and rating >0));
insert into rev values("C01", "Ajay", "007", 3);
insert into rev values("C02", "Akshay", "007", 4);
insert into rev values("C03", "Khrithik", "007", 5);
insert into rev values("C04", "Bhushith", "007", 4);
insert into rev values("C05", "Krishna", "007", 4);
insert into rev values("C06", "Harshit", "007", 5);
insert into rev values("C07", "Nidhish", "007", 1);
select * from rev;
select avg(rating) from rev;
insert into rest values(rating = avg(rev.rating));
update rest set rating = avg(rev.rating) where ID = "007";
